// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countLinks = `-- name: CountLinks :one
SELECT count(*) FROM links
`

func (q *Queries) CountLinks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLinks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLink = `-- name: CreateLink :one
INSERT INTO links (id, slug, target_url, title, expires_at, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, slug, target_url, title, created_at, expires_at, is_active
`

type CreateLinkParams struct {
	ID        uuid.UUID  `json:"id"`
	Slug      string     `json:"slug"`
	TargetUrl string     `json:"target_url"`
	Title     *string    `json:"title"`
	ExpiresAt *time.Time `json:"expires_at"`
	IsActive  bool       `json:"is_active"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink,
		arg.ID,
		arg.Slug,
		arg.TargetUrl,
		arg.Title,
		arg.ExpiresAt,
		arg.IsActive,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TargetUrl,
		&i.Title,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsActive,
	)
	return i, err
}

const deleteLink = `-- name: DeleteLink :execrows
DELETE FROM links WHERE id = $1
`

func (q *Queries) DeleteLink(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLink, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLinkByID = `-- name: GetLinkByID :one
SELECT id, slug, target_url, title, created_at, expires_at, is_active FROM links WHERE id = $1
`

func (q *Queries) GetLinkByID(ctx context.Context, id uuid.UUID) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByID, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TargetUrl,
		&i.Title,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsActive,
	)
	return i, err
}

const getLinkBySlug = `-- name: GetLinkBySlug :one
SELECT id, slug, target_url, title, created_at, expires_at, is_active FROM links WHERE slug = $1
`

func (q *Queries) GetLinkBySlug(ctx context.Context, slug string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkBySlug, slug)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TargetUrl,
		&i.Title,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsActive,
	)
	return i, err
}

const listLinks = `-- name: ListLinks :many
SELECT id, slug, target_url, title, created_at, expires_at, is_active FROM links
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListLinksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListLinks(ctx context.Context, arg ListLinksParams) ([]Link, error) {
	rows, err := q.db.Query(ctx, listLinks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Link{}
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.TargetUrl,
			&i.Title,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const slugExists = `-- name: SlugExists :one
SELECT EXISTS (SELECT 1 FROM links WHERE slug = $1)
`

func (q *Queries) SlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, slugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateLink = `-- name: UpdateLink :one
UPDATE links
SET target_url = $2,
    title      = $3,
    expires_at = $4,
    is_active  = $5
WHERE id = $1
RETURNING id, slug, target_url, title, created_at, expires_at, is_active
`

type UpdateLinkParams struct {
	ID        uuid.UUID  `json:"id"`
	TargetUrl string     `json:"target_url"`
	Title     *string    `json:"title"`
	ExpiresAt *time.Time `json:"expires_at"`
	IsActive  bool       `json:"is_active"`
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, updateLink,
		arg.ID,
		arg.TargetUrl,
		arg.Title,
		arg.ExpiresAt,
		arg.IsActive,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TargetUrl,
		&i.Title,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsActive,
	)
	return i, err
}
