// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countLinks = `-- name: CountLinks :one
SELECT count(*)::bigint
FROM links l
WHERE (
        $1::text = ''
        OR l.slug ILIKE '%' || $1 || '%'
        OR l.target_url ILIKE '%' || $1 || '%'
        OR COALESCE(l.title, '') ILIKE '%' || $1 || '%'
        OR COALESCE(l.campaign, '') ILIKE '%' || $1 || '%'
        OR array_to_string(l.tags, ' ') ILIKE '%' || $1 || '%'
    )
  AND (
        $2::text = ''
        OR ($2 = 'active' AND l.is_active = true AND (l.expires_at IS NULL OR l.expires_at > now()))
        OR ($2 = 'inactive' AND l.is_active = false)
        OR ($2 = 'expired' AND l.is_active = true AND l.expires_at IS NOT NULL AND l.expires_at <= now())
    )
  AND ($3::text = '' OR $3 = ANY(l.tags))
  AND ($4::text = '' OR l.campaign = $4)
`

type CountLinksParams struct {
	Q        string `json:"q"`
	Status   string `json:"status"`
	Tag      string `json:"tag"`
	Campaign string `json:"campaign"`
}

func (q *Queries) CountLinks(ctx context.Context, arg CountLinksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLinks,
		arg.Q,
		arg.Status,
		arg.Tag,
		arg.Campaign,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createLink = `-- name: CreateLink :one
INSERT INTO links (
    id,
    slug,
    target_url,
    title,
    expires_at,
    is_active,
    campaign,
    tags,
    utm_source,
    utm_medium,
    utm_campaign,
    utm_term,
    utm_content,
    notes
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, slug, target_url, title, created_at, expires_at, is_active, campaign, tags, utm_source, utm_medium, utm_campaign, utm_term, utm_content, notes, updated_at
`

type CreateLinkParams struct {
	ID          uuid.UUID  `json:"id"`
	Slug        string     `json:"slug"`
	TargetUrl   string     `json:"target_url"`
	Title       *string    `json:"title"`
	ExpiresAt   *time.Time `json:"expires_at"`
	IsActive    bool       `json:"is_active"`
	Campaign    *string    `json:"campaign"`
	Tags        []string   `json:"tags"`
	UtmSource   *string    `json:"utm_source"`
	UtmMedium   *string    `json:"utm_medium"`
	UtmCampaign *string    `json:"utm_campaign"`
	UtmTerm     *string    `json:"utm_term"`
	UtmContent  *string    `json:"utm_content"`
	Notes       *string    `json:"notes"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink,
		arg.ID,
		arg.Slug,
		arg.TargetUrl,
		arg.Title,
		arg.ExpiresAt,
		arg.IsActive,
		arg.Campaign,
		arg.Tags,
		arg.UtmSource,
		arg.UtmMedium,
		arg.UtmCampaign,
		arg.UtmTerm,
		arg.UtmContent,
		arg.Notes,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TargetUrl,
		&i.Title,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsActive,
		&i.Campaign,
		&i.Tags,
		&i.UtmSource,
		&i.UtmMedium,
		&i.UtmCampaign,
		&i.UtmTerm,
		&i.UtmContent,
		&i.Notes,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLink = `-- name: DeleteLink :execrows
DELETE FROM links WHERE id = $1
`

func (q *Queries) DeleteLink(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLink, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLinkByID = `-- name: GetLinkByID :one
SELECT id, slug, target_url, title, created_at, expires_at, is_active, campaign, tags, utm_source, utm_medium, utm_campaign, utm_term, utm_content, notes, updated_at FROM links WHERE id = $1
`

func (q *Queries) GetLinkByID(ctx context.Context, id uuid.UUID) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByID, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TargetUrl,
		&i.Title,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsActive,
		&i.Campaign,
		&i.Tags,
		&i.UtmSource,
		&i.UtmMedium,
		&i.UtmCampaign,
		&i.UtmTerm,
		&i.UtmContent,
		&i.Notes,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinkBySlug = `-- name: GetLinkBySlug :one
SELECT id, slug, target_url, title, created_at, expires_at, is_active, campaign, tags, utm_source, utm_medium, utm_campaign, utm_term, utm_content, notes, updated_at FROM links WHERE slug = $1
`

func (q *Queries) GetLinkBySlug(ctx context.Context, slug string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkBySlug, slug)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TargetUrl,
		&i.Title,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsActive,
		&i.Campaign,
		&i.Tags,
		&i.UtmSource,
		&i.UtmMedium,
		&i.UtmCampaign,
		&i.UtmTerm,
		&i.UtmContent,
		&i.Notes,
		&i.UpdatedAt,
	)
	return i, err
}

const listLinks = `-- name: ListLinks :many
SELECT
    l.id, l.slug, l.target_url, l.title, l.created_at, l.expires_at, l.is_active, l.campaign, l.tags, l.utm_source, l.utm_medium, l.utm_campaign, l.utm_term, l.utm_content, l.notes, l.updated_at,
    COALESCE(ld.total_clicks, 0)::bigint AS total_clicks,
    COALESCE(lc.last_clicked_at, '1970-01-01 00:00:00+00'::timestamptz) AS last_clicked_at,
    (lc.last_clicked_at IS NOT NULL)::boolean AS has_last_clicked_at
FROM links l
LEFT JOIN (
    SELECT link_id, sum(clicks)::bigint AS total_clicks
    FROM link_daily
    GROUP BY link_id
) ld ON ld.link_id = l.id
LEFT JOIN (
    SELECT link_id, max(created_at)::timestamptz AS last_clicked_at
    FROM clicks
    GROUP BY link_id
) lc ON lc.link_id = l.id
WHERE (
        $1::text = ''
        OR l.slug ILIKE '%' || $1 || '%'
        OR l.target_url ILIKE '%' || $1 || '%'
        OR COALESCE(l.title, '') ILIKE '%' || $1 || '%'
        OR COALESCE(l.campaign, '') ILIKE '%' || $1 || '%'
        OR array_to_string(l.tags, ' ') ILIKE '%' || $1 || '%'
    )
  AND (
        $2::text = ''
        OR ($2 = 'active' AND l.is_active = true AND (l.expires_at IS NULL OR l.expires_at > now()))
        OR ($2 = 'inactive' AND l.is_active = false)
        OR ($2 = 'expired' AND l.is_active = true AND l.expires_at IS NOT NULL AND l.expires_at <= now())
    )
  AND ($3::text = '' OR $3 = ANY(l.tags))
  AND ($4::text = '' OR l.campaign = $4)
ORDER BY l.created_at DESC
LIMIT $6 OFFSET $5
`

type ListLinksParams struct {
	Q        string `json:"q"`
	Status   string `json:"status"`
	Tag      string `json:"tag"`
	Campaign string `json:"campaign"`
	Offset   int32  `json:"offset"`
	Limit    int32  `json:"limit"`
}

type ListLinksRow struct {
	ID               uuid.UUID  `json:"id"`
	Slug             string     `json:"slug"`
	TargetUrl        string     `json:"target_url"`
	Title            *string    `json:"title"`
	CreatedAt        time.Time  `json:"created_at"`
	ExpiresAt        *time.Time `json:"expires_at"`
	IsActive         bool       `json:"is_active"`
	Campaign         *string    `json:"campaign"`
	Tags             []string   `json:"tags"`
	UtmSource        *string    `json:"utm_source"`
	UtmMedium        *string    `json:"utm_medium"`
	UtmCampaign      *string    `json:"utm_campaign"`
	UtmTerm          *string    `json:"utm_term"`
	UtmContent       *string    `json:"utm_content"`
	Notes            *string    `json:"notes"`
	UpdatedAt        time.Time  `json:"updated_at"`
	TotalClicks      int64      `json:"total_clicks"`
	LastClickedAt    time.Time  `json:"last_clicked_at"`
	HasLastClickedAt bool       `json:"has_last_clicked_at"`
}

func (q *Queries) ListLinks(ctx context.Context, arg ListLinksParams) ([]ListLinksRow, error) {
	rows, err := q.db.Query(ctx, listLinks,
		arg.Q,
		arg.Status,
		arg.Tag,
		arg.Campaign,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinksRow{}
	for rows.Next() {
		var i ListLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.TargetUrl,
			&i.Title,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.IsActive,
			&i.Campaign,
			&i.Tags,
			&i.UtmSource,
			&i.UtmMedium,
			&i.UtmCampaign,
			&i.UtmTerm,
			&i.UtmContent,
			&i.Notes,
			&i.UpdatedAt,
			&i.TotalClicks,
			&i.LastClickedAt,
			&i.HasLastClickedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const slugExists = `-- name: SlugExists :one
SELECT EXISTS (SELECT 1 FROM links WHERE slug = $1)
`

func (q *Queries) SlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, slugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateLink = `-- name: UpdateLink :one
UPDATE links
SET target_url   = $2,
    title        = $3,
    expires_at   = $4,
    is_active    = $5,
    campaign     = $6,
    tags         = $7,
    utm_source   = $8,
    utm_medium   = $9,
    utm_campaign = $10,
    utm_term     = $11,
    utm_content  = $12,
    notes        = $13,
    updated_at   = now()
WHERE id = $1
RETURNING id, slug, target_url, title, created_at, expires_at, is_active, campaign, tags, utm_source, utm_medium, utm_campaign, utm_term, utm_content, notes, updated_at
`

type UpdateLinkParams struct {
	ID          uuid.UUID  `json:"id"`
	TargetUrl   string     `json:"target_url"`
	Title       *string    `json:"title"`
	ExpiresAt   *time.Time `json:"expires_at"`
	IsActive    bool       `json:"is_active"`
	Campaign    *string    `json:"campaign"`
	Tags        []string   `json:"tags"`
	UtmSource   *string    `json:"utm_source"`
	UtmMedium   *string    `json:"utm_medium"`
	UtmCampaign *string    `json:"utm_campaign"`
	UtmTerm     *string    `json:"utm_term"`
	UtmContent  *string    `json:"utm_content"`
	Notes       *string    `json:"notes"`
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, updateLink,
		arg.ID,
		arg.TargetUrl,
		arg.Title,
		arg.ExpiresAt,
		arg.IsActive,
		arg.Campaign,
		arg.Tags,
		arg.UtmSource,
		arg.UtmMedium,
		arg.UtmCampaign,
		arg.UtmTerm,
		arg.UtmContent,
		arg.Notes,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TargetUrl,
		&i.Title,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsActive,
		&i.Campaign,
		&i.Tags,
		&i.UtmSource,
		&i.UtmMedium,
		&i.UtmCampaign,
		&i.UtmTerm,
		&i.UtmContent,
		&i.Notes,
		&i.UpdatedAt,
	)
	return i, err
}
