// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Click struct {
	ID         uuid.UUID  `json:"id"`
	LinkID     uuid.UUID  `json:"link_id"`
	CreatedAt  time.Time  `json:"created_at"`
	IpHash     string     `json:"ip_hash"`
	Referrer   *string    `json:"referrer"`
	UaRaw      string     `json:"ua_raw"`
	DeviceType *string    `json:"device_type"`
	Browser    *string    `json:"browser"`
	Os         *string    `json:"os"`
	Country    *string    `json:"country"`
	City       *string    `json:"city"`
	EnrichedAt *time.Time `json:"enriched_at"`
}

type Link struct {
	ID        uuid.UUID  `json:"id"`
	Slug      string     `json:"slug"`
	TargetUrl string     `json:"target_url"`
	Title     *string    `json:"title"`
	CreatedAt time.Time  `json:"created_at"`
	ExpiresAt *time.Time `json:"expires_at"`
	IsActive  bool       `json:"is_active"`
}

type LinkDaily struct {
	LinkID uuid.UUID   `json:"link_id"`
	Day    pgtype.Date `json:"day"`
	Clicks int32       `json:"clicks"`
}
